// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// IB
double IB(const arma::sp_mat& W, const arma::vec& s);
RcppExport SEXP _wave_IB(SEXP WSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(IB(W, s));
    return rcpp_result_gen;
END_RCPP
}
// distUnitk
arma::vec distUnitk(arma::mat X, int k, bool tore, double toreBound);
RcppExport SEXP _wave_distUnitk(SEXP XSEXP, SEXP kSEXP, SEXP toreSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(distUnitk(X, k, tore, toreBound));
    return rcpp_result_gen;
END_RCPP
}
// projOp
arma::vec projOp(arma::vec v, arma::vec u);
RcppExport SEXP _wave_projOp(SEXP vSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(projOp(v, u));
    return rcpp_result_gen;
END_RCPP
}
// QRarma
Rcpp::List QRarma(arma::mat A);
RcppExport SEXP _wave_QRarma(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(QRarma(A));
    return rcpp_result_gen;
END_RCPP
}
// SVDarma
Rcpp::List SVDarma(arma::mat A);
RcppExport SEXP _wave_SVDarma(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(SVDarma(A));
    return rcpp_result_gen;
END_RCPP
}
// wave
arma::vec wave(const arma::mat& X, const arma::vec& pik, double bound, bool tore, bool jitter, bool oneD, bool comment);
RcppExport SEXP _wave_wave(SEXP XSEXP, SEXP pikSEXP, SEXP boundSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP oneDSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< bool >::type oneD(oneDSEXP);
    Rcpp::traits::input_parameter< bool >::type comment(commentSEXP);
    rcpp_result_gen = Rcpp::wrap(wave(X, pik, bound, tore, jitter, oneD, comment));
    return rcpp_result_gen;
END_RCPP
}
// wave2
arma::vec wave2(const arma::mat& X, const arma::vec& pik, double bound, bool tore, bool jitter, bool oneD, bool comment);
RcppExport SEXP _wave_wave2(SEXP XSEXP, SEXP pikSEXP, SEXP boundSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP oneDSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< bool >::type oneD(oneDSEXP);
    Rcpp::traits::input_parameter< bool >::type comment(commentSEXP);
    rcpp_result_gen = Rcpp::wrap(wave2(X, pik, bound, tore, jitter, oneD, comment));
    return rcpp_result_gen;
END_RCPP
}
// wpik
arma::sp_mat wpik(arma::mat X, arma::vec pik, double bound, bool tore, bool jitter, double toreBound);
RcppExport SEXP _wave_wpik(SEXP XSEXP, SEXP pikSEXP, SEXP boundSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(wpik(X, pik, bound, tore, jitter, toreBound));
    return rcpp_result_gen;
END_RCPP
}
// wpik2
arma::sp_mat wpik2(arma::mat X, arma::vec pik, bool tore, bool jitter, double toreBound);
RcppExport SEXP _wave_wpik2(SEXP XSEXP, SEXP pikSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(wpik2(X, pik, tore, jitter, toreBound));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wave_IB", (DL_FUNC) &_wave_IB, 2},
    {"_wave_distUnitk", (DL_FUNC) &_wave_distUnitk, 4},
    {"_wave_projOp", (DL_FUNC) &_wave_projOp, 2},
    {"_wave_QRarma", (DL_FUNC) &_wave_QRarma, 1},
    {"_wave_SVDarma", (DL_FUNC) &_wave_SVDarma, 1},
    {"_wave_wave", (DL_FUNC) &_wave_wave, 7},
    {"_wave_wave2", (DL_FUNC) &_wave_wave2, 7},
    {"_wave_wpik", (DL_FUNC) &_wave_wpik, 6},
    {"_wave_wpik2", (DL_FUNC) &_wave_wpik2, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_wave(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
