// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// IB
double IB(const arma::sp_mat& W, const arma::vec& s);
RcppExport SEXP _wave_IB(SEXP WSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(IB(W, s));
    return rcpp_result_gen;
END_RCPP
}
// distUnitk
arma::vec distUnitk(arma::mat X, int k, bool tore, double toreBound);
RcppExport SEXP _wave_distUnitk(SEXP XSEXP, SEXP kSEXP, SEXP toreSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(distUnitk(X, k, tore, toreBound));
    return rcpp_result_gen;
END_RCPP
}
// sb_vk
arma::vec sb_vk(arma::vec pik, arma::mat X, arma::vec s);
RcppExport SEXP _wave_sb_vk(SEXP pikSEXP, SEXP XSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sb_vk(pik, X, s));
    return rcpp_result_gen;
END_RCPP
}
// wave
arma::vec wave(const arma::mat& X, const arma::vec& pik, double bound, bool tore, bool jitter, bool oneD, bool comment);
RcppExport SEXP _wave_wave(SEXP XSEXP, SEXP pikSEXP, SEXP boundSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP oneDSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< bool >::type oneD(oneDSEXP);
    Rcpp::traits::input_parameter< bool >::type comment(commentSEXP);
    rcpp_result_gen = Rcpp::wrap(wave(X, pik, bound, tore, jitter, oneD, comment));
    return rcpp_result_gen;
END_RCPP
}
// wpik
arma::sp_mat wpik(arma::mat X, arma::vec pik, double bound, bool tore, bool jitter, double toreBound);
RcppExport SEXP _wave_wpik(SEXP XSEXP, SEXP pikSEXP, SEXP boundSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(wpik(X, pik, bound, tore, jitter, toreBound));
    return rcpp_result_gen;
END_RCPP
}
// wpikInv
arma::sp_mat wpikInv(arma::mat X, arma::vec pik, bool tore, bool jitter, double toreBound);
RcppExport SEXP _wave_wpikInv(SEXP XSEXP, SEXP pikSEXP, SEXP toreSEXP, SEXP jitterSEXP, SEXP toreBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< bool >::type tore(toreSEXP);
    Rcpp::traits::input_parameter< bool >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< double >::type toreBound(toreBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(wpikInv(X, pik, tore, jitter, toreBound));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wave_IB", (DL_FUNC) &_wave_IB, 2},
    {"_wave_distUnitk", (DL_FUNC) &_wave_distUnitk, 4},
    {"_wave_sb_vk", (DL_FUNC) &_wave_sb_vk, 3},
    {"_wave_wave", (DL_FUNC) &_wave_wave, 7},
    {"_wave_wpik", (DL_FUNC) &_wave_wpik, 6},
    {"_wave_wpikInv", (DL_FUNC) &_wave_wpikInv, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_wave(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
