# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Spatial balance based on Moran's I index
#'
#' @description
#'
#' This function implements the method from
#'
#' @param W A matrix representing the spatial weights indicating how close is the jth unit to the ith.
#' @param s A numeric vector of 0 and 1 that represent the sample.
#'
#' @return A numeric value that represent the spatial spreading measure.
#' @export
IBarma <- function(W, s) {
    .Call(`_wave_IBarma`, W, s)
}

#' @title Euclidean distance with tore option
#'
#' @description
#' Calculate the distance from the unit k to the other units.
#'
#'
#' @param X A matrix of size N x 2, it should represent the 2D position of the units.
#' @param k An integer value, the index of the unit.
#' @param tore logical, if we are considering the distance on a tore. Default is TRUE.
#' @param toreBound A numeric value that specify the size of the grid.
#'
#' @return A vector that represent the distance values.
#'
#'
#' @export
distUnitk <- function(X, k, tore, toreBound) {
    .Call(`_wave_distUnitk`, X, k, tore, toreBound)
}

#' @title Projection operator
#'
#' @description
#'
#' This operator projects the vector v orthogonally onto the line spanned by vector u.
#'
#'
#' @param v vector that is projected.
#' @parma u vector on which we project.
#'
#' @return The projection of the vector v onto the line spanned by the vector u.
#' @export
projOp <- function(v, u) {
    .Call(`_wave_projOp`, v, u)
}

#' @title column sum on sparse matrix
#'
#' @description
#' column sum that iterate only on the non-zero entries of the matrix.
#'
#' @param x A sparse matrix
#'
#' @return column sum of the sparse matrix
#'
#' @export
#'
colSumsiter <- function(x) {
    .Call(`_wave_colSumsiter`, x)
}

#' @title row sum on sparse matrix
#'
#' @description
#' row sum that iterate only on the non-zero entries of the matrix.
#'
#' @param x A sparse matrix
#'
#' @return row sum of the sparse matrix
#'
#' @export
#'
rowSumsiter <- function(x) {
    .Call(`_wave_rowSumsiter`, x)
}

#' @title spreadcube implemented in RcppArmadillo
#'
#' @description
#'
#' Same as spreadcube but with RcppArmadillo implementation.
#'
#' @param X A matrix of size N x 2, it should represent the 2D position of the units.
#' @param pik vector of inclusion probabilites.
#' @param bound bound to reached before a new strata is considered. Default is 1.
#' @param tore logical, if we are considering the distance on a tore. Default is TRUE.
#' @param jitter logical, if you would use a jitter perturbation. See Details for more infomrations. Default is FALSE.
#' @param toreBound A numeric value that specify the size of the grid.
#'
#' @return A sparse matrix.
#' @export
wave <- function(X, pik, tore = TRUE, jitter = TRUE, oneD = FALSE, comment = FALSE) {
    .Call(`_wave_wave`, X, pik, tore, jitter, oneD, comment)
}

#' @title Weights calculated from pik
#'
#' @description
#'
#' The weights are calculated in a way that a unit represents its neighbor till their inclusion probabilities sum to 1.
#' Hence each line represent a strata centered around the unit i and that sum up to 1.
#'
#' @param X A matrix of size N x 2, it should represent the 2D position of the units.
#' @param pik vector of inclusion probabilites.
#' @param bound bound to reached before a new strata is considered. Default is 1.
#' @param tore logical, if we are considering the distance on a tore. Default is TRUE.
#' @param jitter logical, if you would use a jitter perturbation. See Details for more infomrations. Default is FALSE.
#' @param toreBound A numeric value that specify the size of the grid.
#'
#' @return A sparse matrix.
#' @export
wpik <- function(X, pik, bound, tore, jitter, toreBound) {
    .Call(`_wave_wpik`, X, pik, bound, tore, jitter, toreBound)
}

